/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_frinika_priority_Priority */

#ifndef _Included_com_frinika_priority_Priority
#define _Included_com_frinika_priority_Priority
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_frinika_priority_Priority
 * Method:    setPriorityRR
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_frinika_priority_Priority_setPriorityRR
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_frinika_priority_Priority
 * Method:    setPriorityFIFO
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_frinika_priority_Priority_setPriorityFIFO
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_frinika_priority_Priority
 * Method:    setPriorityOTHER
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_frinika_priority_Priority_setPriorityOTHER
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_frinika_priority_Priority
 * Method:    display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_frinika_priority_Priority_display
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
