/* Generated by Together */

package com.frinika.toot;

import uk.org.toot.audio.server.spi.AudioServerServiceProvider;
import uk.org.toot.audio.id.ProviderId;
import com.frinika.toot.javasoundmultiplexed.MultiplexedJavaSoundAudioServer;

public class FrinikaAudioServerServiceProvider extends AudioServerServiceProvider
{
    public FrinikaAudioServerServiceProvider() {
        super(ProviderId.FRINIKA_PROVIDER_ID, "Frinika", "Frinika Audio Servers", "0.1");
        add(MultiplexedJavaSoundAudioServer.class, "JavaSound (multiplexed)", "multiplexed", "0.2");
        // if X available add an X provider
		if (System.getProperty("os.name").equals("Linux")) {
//	        add(ChoppedJackAudioServer.class, "Jack", "chopped", "0.2");
		}	
    }
}
